name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    name: Ruff lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install ruff
        run: pip install ruff
      - name: Run ruff
        run: ruff check .

  types:
    name: Mypy type check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          pip install .[dev]
          pip install mypy
      - name: Run mypy
        run: mypy src

  tests:
    name: Tests (pytest + coverage)
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11"]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"
      - name: Install dependencies
        run: |
          pip install .[dev]
          pip install pytest pytest-cov
      - name: Run tests with coverage
        run: pytest --cov=src --cov-report=term-missing --cov-fail-under=75
      - name: Run pre-commit hooks
        run: |
          pip install pre-commit
          pre-commit run --all-files
